name: Test ci/cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
          go_version: '1.22.1'

    - name: Build Go
      run: go build -v ./...
      
    - name: Test Go
      run: go test -v ./...